### ISSUE TITLE
Fix width/height attributes in svg images

### ISSUE THREAD

**Issue by ondrej-fabry** [ligato/ligato.io#14]
Some of the svg images are not shown properly at currently deployed site. 

This is how it looks for me:

![image](https://user-images.githubusercontent.com/32484950/57684412-070b3f80-7636-11e9-84c4-82bd23fda945.png)

It seems the cause is the missing width/height attributes.

This image does NOT have width/height attributes and is not shown:
https://github.com/ligato/ligato.io/blob/958e5a6fdf173e5b28bfff559cfc23522b8ddd6a/static/images/illustrations/icons/mouse-globe2.svg#L3

This image has width/height attributes and is shown ok:
https://github.com/ligato/ligato.io/blob/958e5a6fdf173e5b28bfff559cfc23522b8ddd6a/static/images/illustrations/icons/calendar-full.svg#L4

@chrismetz09 Try to ensure that everything looks OK by viewing the site deployed in the PR, before merging it.

**Comment by chrismetz09** [comment]
FF does not handle hugo-fresh SVGs in section2 but chrome does. Apparently FF vs Chrome SVG problems encountered many times before.  Attempted to resolve but too much time/testing needed. Repeated workflow for SVGs that FF and Chrome did display okay but this time for the problematic hugo-fresh SVG:

1.  imported SVG image into Sketch. 
2. copied SVG code (sketch option)
3. pasted SVG code into a sublime 2 file. saved as SVG. Note: Sketch generated different SVG code than what was in original.
4. Moved to project ../icons folder
5. opened svg file, set height/width to 150px and then messed around with viewbox to pan/zoom image.
6. updated config.yaml file

Please doublecheck
